export const state = {
  teachers: [],
  classes: [],
  sessions: [],
  swimSlots: [],
  swimSlotKeys: new Set(),
  programActivities: [],
  programLocations: [],
  programTemplates: [],
  selectedProgramWeekType: "A",
  selectedProgramDay: "Lundi",
  desiderataSlots: [],
  desiderataSlotStatus: new Map(),
  desiderataDraft: new Map(),
  desiderataDraftTeacherId: "",
  desiderataDirty: false,
  desiderataPaintStatus: null,
  desiderataPointerDown: false,
  desiderataMouseupBound: false,
  selectedPublicTeacherId: "__ALL__",
  selectedDesiderataTeacherId: "",
  editingTeacherId: "",
  selectedAdminTeacherId: "",
  selectedAdminTeacherIds: [],
  showGlobalPlanner: true,
  selectedGlobalWeekType: "A",
  selectedGlobalPlannerLayout: "GRID",
  globalPicker: null,
  assignModal: null,
  selectedAdminTab: "creation",
  adminSidebarCollapsed: false,
  programEditSessionId: "",
  adminPicker: null,
};
